import type { Property } from './types';

export const featuredProperties: Property[] = [
  {
    id: 'demo-1',
    title: 'Banesë moderne me pamje',
    location: 'Ulpianë, Prishtinë',
    priceLabel: '€101,200',
    areaLabel: '151 m²',
    roomsLabel: '3 Dhoma',
    typeLabel: 'Banesë',
    badge: 'gold',
    deal: 'sale',
    isFavorite: false,
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'demo-2',
    title: 'Apartament premium',
    location: 'Prishtinë',
    priceLabel: '€850 / muaj',
    areaLabel: '118 m²',
    roomsLabel: '4 Dhoma',
    typeLabel: 'Apartament',
    badge: 'premium',
    deal: 'rent',
    isFavorite: true,
    imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'demo-3',
    title: 'Shtëpi familjare',
    location: 'Veternik, Prishtinë',
    priceLabel: '€245,000',
    areaLabel: '220 m²',
    roomsLabel: '5 Dhoma',
    typeLabel: 'Shtëpi',
    badge: 'boost',
    deal: 'sale',
    isFavorite: false,
    imageUrl: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80',
  },
];
