import type { Property } from './types';

export const featuredProperties: Property[] = [
  {
    id: 'demo-1',
    title: 'Banesë moderne me pamje',
    location: 'Ulpianë, Prishtinë',
    priceLabel: '€101,200',
    areaLabel: '151 m²',
    roomsLabel: '3 Dhoma',
    typeLabel: 'Banesë',
    badge: 'gold',
    deal: 'sale',
    isFavorite: false,
  },
  {
    id: 'demo-2',
    title: 'Apartament premium',
    location: 'Prishtinë',
    priceLabel: '€850 / muaj',
    areaLabel: '118 m²',
    roomsLabel: '4 Dhoma',
    typeLabel: 'Apartament',
    badge: 'premium',
    deal: 'rent',
    isFavorite: true,
  },
  {
    id: 'demo-3',
    title: 'Shtëpi familjare',
    location: 'Veternik, Prishtinë',
    priceLabel: '€245,000',
    areaLabel: '220 m²',
    roomsLabel: '5 Dhoma',
    typeLabel: 'Shtëpi',
    badge: 'boost',
    deal: 'sale',
    isFavorite: false,
  },
];
